name: ra_env
channels:
    - conda-forge
dependencies:
    - python==3.6.3
    - pip==21.2.4
    - matplotlib==2.1.1
    - jupyter==1.0.0
    - future==0.16.0
    - lxml==4.1.1
    - networkx==2.1
    - scikit-image==0.13.1
    - scipy==1.0.0
    - pip:
        - visdom==0.1.7
        - bresenham==0.2
        - shapely==1.7.1
